# Generated by Django 4.2.16 on 2024-12-17 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35, verbose_name='Название категории')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Наименование задачи')),
                ('desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание задачи')),
                ('done', models.BooleanField(default=False, verbose_name='Отметка о выполнеии')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Taskich.category', verbose_name='Категория')),
            ],
        ),
    ]
