# Generated by Django 4.2.16 on 2024-12-22 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatFin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cat', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Задача'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'createdAt')},
        ),
        migrations.CreateModel(
            name='Finance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameF', models.TextField()),
                ('desc', models.TextField()),
                ('Income', models.BooleanField(default=None)),
                ('count', models.BigIntegerField(default=0)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Taskich.catfin')),
            ],
        ),
    ]
