# Generated by Django 4.2.16 on 2024-12-26 08:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryMoney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Наименование категории')),
            ],
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-createdAt'], 'verbose_name': 'Задача'},
        ),
        migrations.AlterUniqueTogether(
            name='task',
            unique_together={('title', 'createdAt')},
        ),
        migrations.CreateModel(
            name='Money',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Наименование транзакции')),
                ('type_money', models.BooleanField(null=True, verbose_name='Тип транзакции')),
                ('value', models.BigIntegerField(verbose_name='Сумма')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Taskich.categorymoney', verbose_name='Категория')),
            ],
            options={
                'ordering': ['-createdAt'],
            },
        ),
    ]
