# Generated by Django 4.2.16 on 2024-12-26 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0002_categorymoney_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='money',
            name='type_money',
            field=models.CharField(choices=[('i', 'Доход'), ('d', 'Расход')], default='i', max_length=1),
        ),
    ]
