# Generated by Django 4.2.16 on 2025-01-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0003_alter_money_type_money'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorymoney',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='money',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
