# Generated by Django 4.2.16 on 2024-12-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0003_alter_finance_category_alter_finance_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='Income',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='finance',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='Taskich.catfin', verbose_name='Категория'),
        ),
    ]
