# Generated by Django 4.2.16 on 2024-12-24 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0004_alter_finance_income_alter_finance_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='finance',
            name='Income',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
