# Generated by Django 4.2.16 on 2025-01-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0004_categorymoney_slug_money_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='dead_line',
            field=models.DateField(auto_now=True, null=True, verbose_name='Дедлайн'),
        ),
    ]
