# Generated by Django 4.2.16 on 2025-01-13 21:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0007_alter_task_dead_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dead_line',
            field=models.DateField(default=datetime.datetime.now, null=True, verbose_name='Дедлайн'),
        ),
    ]
