# Generated by Django 4.2.16 on 2025-01-14 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Taskich', '0008_alter_task_dead_line'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryZametki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('J', 'Рабочая'), ('EDL', 'Бытовая')], default='EDL', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Zametki',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Название заметки')),
                ('text', models.TextField(verbose_name='Основной текст')),
                ('edited', models.DateTimeField(auto_now_add=True, verbose_name='Изменено')),
                ('createdAt', models.DateTimeField(auto_now=True, verbose_name='Создано')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Taskich.categoryzametki', verbose_name='Категория')),
            ],
        ),
    ]
